# Generated by Django 3.1.3 on 2020-11-07 17:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201104_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='designation',
            field=models.CharField(choices=[('S', 'Student'), ('F', 'Faculty')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='education',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='experience',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='expertise',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('-', 'Prefer not to say')], default='-', max_length=1),
        ),
        migrations.AddField(
            model_name='account',
            name='introduction',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='mobile',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='account',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=1, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='account',
            name='social_handles',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='needs_urgent_mentoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentee',
            name='topics',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='is_open_to_mentorship',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentee_group_size',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentee_types',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentorship_duration',
            field=models.IntegerField(default=6, help_text='In months', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.CreateModel(
            name='MentorMentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentor')),
            ],
        ),
    ]
