# Generated by Django 3.1.3 on 2020-11-07 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201107_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyMentees',
            new_name='MyMentee',
        ),
        migrations.RenameModel(
            old_name='MyMentors',
            new_name='MyMentor',
        ),
        migrations.RenameModel(
            old_name='PendingMenteeshipRequests',
            new_name='PendingMenteeshipRequest',
        ),
        migrations.RenameModel(
            old_name='PendingMentorshipRequests',
            new_name='PendingMentorshipRequest',
        ),
    ]
