# Generated by Django 3.1.3 on 2020-11-18 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201115_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeexpectedrolefield',
            name='field',
            field=models.IntegerField(choices=[(1, 'CS'), (2, 'ECE'), (3, 'CSD'), (4, 'CSAM'), (5, 'CSSS'), (6, 'CSAI')], null=True),
        ),
        migrations.AlterField(
            model_name='menteerolefield',
            name='field',
            field=models.IntegerField(choices=[(1, 'CS'), (2, 'ECE'), (3, 'CSD'), (4, 'CSAM'), (5, 'CSSS'), (6, 'CSAI')], null=True),
        ),
        migrations.AlterField(
            model_name='mentorexpectedrolefield',
            name='field',
            field=models.IntegerField(choices=[(1, 'CS'), (2, 'ECE'), (3, 'CSD'), (4, 'CSAM'), (5, 'CSSS'), (6, 'CSAI')], null=True),
        ),
        migrations.AlterField(
            model_name='mentorrolefield',
            name='field',
            field=models.IntegerField(choices=[(1, 'CS'), (2, 'ECE'), (3, 'CSD'), (4, 'CSAM'), (5, 'CSSS'), (6, 'CSAI')], null=True),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=512, null=True)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reciever', to='users.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='users.account')),
            ],
        ),
    ]
