# Generated by Django 3.1.3 on 2020-11-19 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201119_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Meeting', max_length=64)),
                ('agenda', models.CharField(default='', max_length=128)),
                ('time', models.DateTimeField()),
                ('meeting_url', models.URLField(default='www.meet.google.com', max_length=128)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_creator', to='users.account')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_guest', to='users.account')),
            ],
        ),
    ]
