# Generated by Django 3.1.3 on 2020-12-18 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_mentorarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorarea',
            name='mentor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.mentor'),
        ),
    ]
