# Generated by Django 3.1.3 on 2020-12-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20201219_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeexpectedrolefield',
            name='role',
            field=models.IntegerField(choices=[(1, 'BTech'), (2, 'MTech'), (3, 'PhD'), (4, 'Faculty'), (5, 'Developer')], null=True),
        ),
        migrations.AlterField(
            model_name='menteerolefield',
            name='role',
            field=models.IntegerField(choices=[(1, 'BTech'), (2, 'MTech'), (3, 'PhD'), (4, 'Faculty'), (5, 'Developer')], null=True),
        ),
        migrations.AlterField(
            model_name='mentorexpectedrolefield',
            name='role',
            field=models.IntegerField(choices=[(1, 'BTech'), (2, 'MTech'), (3, 'PhD'), (4, 'Faculty'), (5, 'Developer')], null=True),
        ),
        migrations.AlterField(
            model_name='mentorrolefield',
            name='role',
            field=models.IntegerField(choices=[(1, 'BTech'), (2, 'MTech'), (3, 'PhD'), (4, 'Faculty'), (5, 'Developer')], null=True),
        ),
    ]
