# Generated by Django 3.1.3 on 2020-12-22 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_delete_mentorsentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField()),
                ('meeting_length', models.IntegerField(max_length=1)),
                ('meeting_details', models.TextField(max_length=512)),
                ('meeting_todos', models.TextField(max_length=512, null=True)),
                ('next_meeting_date', models.DateTimeField()),
                ('next_meeting_agenda', models.TextField(max_length=512)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentor')),
            ],
        ),
    ]
