# Generated by Django 3.1.3 on 2020-12-22 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_delete_mentorsentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorrolefield',
            name='mentor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.mentor'),
        ),
    ]
