# Generated by Django 3.1.3 on 2020-12-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_meetingsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingsummary',
            name='meeting_length',
            field=models.IntegerField(),
        ),
    ]
