# Generated by Django 3.1.3 on 2020-12-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20201231_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='other_responsibility',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='responsibility1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='responsibility2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='responsibility3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='responsibility4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='responsibility5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='responsibility6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='responsibility7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='responsibility8',
            field=models.BooleanField(default=False),
        ),
    ]
