# Generated by Django 3.1.3 on 2021-01-01 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20201231_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentorship_duration',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
