# Generated by Django 3.1.3 on 2021-01-06 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20210107_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedmentormenteerelation',
            name='date_ended',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
