# Generated by Django 3.1.3 on 2021-01-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20210107_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounteducation',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accounteducation',
            name='organization',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='accounteducation',
            name='qualification',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='accounteducation',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accountresearchexperience',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accountresearchexperience',
            name='organization',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='accountresearchexperience',
            name='position',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='accountresearchexperience',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
