# Generated by Django 3.1.3 on 2020-11-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentorship_duration',
            field=models.IntegerField(null=True),
        ),
    ]
