# Generated by Django 3.1.3 on 2020-11-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201104_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentee',
            old_name='user',
            new_name='account',
        ),
    ]
