# Generated by Django 3.1.3 on 2020-11-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201104_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='user',
            new_name='account',
        ),
    ]
