# Generated by Django 3.1.3 on 2020-11-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201107_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PendingMentorshipRequest',
            new_name='MenteeSentRequest',
        ),
        migrations.RenameModel(
            old_name='PendingMenteeshipRequest',
            new_name='MentorSentRequest',
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('-', 'Prefer not to say')], default='-', max_length=1),
        ),
    ]
