# Generated by Django 3.1.3 on 2020-11-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201108_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='mentee_types',
        ),
        migrations.CreateModel(
            name='TypesOfMentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_types', models.CharField(choices=[('B', 'BTech'), ('P', 'PhD'), ('CSE', 'Computer Science'), ('F', 'Faculty'), ('ECE', 'Electronics And Communication')], max_length=3, null=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentee')),
            ],
        ),
        migrations.CreateModel(
            name='TypesOfMentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee_types', models.CharField(choices=[('B', 'BTech'), ('P', 'PhD'), ('CSE', 'Computer Science'), ('F', 'Faculty'), ('ECE', 'Electronics And Communication')], max_length=3, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentor')),
            ],
        ),
    ]
