# Generated by Django 3.1.3 on 2020-11-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201109_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typesofmentee',
            old_name='mentee_types',
            new_name='mentee_type',
        ),
        migrations.RenameField(
            model_name='typesofmentor',
            old_name='mentor_types',
            new_name='mentor_type',
        ),
    ]
