# Generated by Django 3.1.3 on 2020-12-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201219_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorarea',
            name='subarea',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mentorarea',
            name='area',
            field=models.IntegerField(choices=[(1, 'Algorithms and Complexity'), (2, 'Artificial Intelligence'), (3, 'Computational Bio and Bioinformatics'), (4, 'Computer Architecture'), (5, 'Computer Graphics'), (6, 'Computer Networks'), (7, 'Computer Security'), (8, 'Computer Vision'), (9, 'Cryptography'), (10, 'Databases'), (11, 'Design Automation'), (12, 'Economics and Computation'), (13, 'Embedded and Real-Time Systems'), (14, 'High-Performance Computing'), (15, 'Human-Computer Interaction'), (16, 'Logic and Verification'), (17, 'Machine Learning and Data Mining'), (18, 'Measurement and Performance Analysis'), (19, 'Mobile Computing'), (20, 'Natural Language Processing'), (21, 'Operating Systems'), (22, 'Programming Languages'), (23, 'Robotics'), (24, 'Software Engineering'), (25, 'The Web and Information Retrieval'), (26, 'Visualization')], null=True),
        ),
    ]
