# Generated by Django 3.1.3 on 2020-12-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20201219_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorexpectedrolefield',
            name='role',
            field=models.IntegerField(choices=[(1, 'Faculty'), (2, 'Developer')], null=True),
        ),
        migrations.AlterField(
            model_name='mentorrolefield',
            name='role',
            field=models.IntegerField(choices=[(1, 'Faculty'), (2, 'Developer')], null=True),
        ),
    ]
