# Generated by Django 3.1.3 on 2020-12-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20201219_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeexpectedrolefield',
            name='role',
            field=models.IntegerField(choices=[(1, 'Faculty'), (2, 'Developer'), (3, 'BTech'), (4, 'MTech'), (5, 'PhD')], null=True),
        ),
        migrations.AlterField(
            model_name='menteerolefield',
            name='role',
            field=models.IntegerField(choices=[(1, 'Faculty'), (2, 'Developer'), (3, 'BTech'), (4, 'MTech'), (5, 'PhD')], null=True),
        ),
    ]
