# Generated by Django 3.1.3 on 2020-12-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201219_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeexpectedrolefield',
            name='field',
            field=models.IntegerField(choices=[(1, 'CSE'), (2, 'ECE'), (3, 'CSD'), (4, 'CSAM'), (5, 'CSSS'), (6, 'CSAI')], null=True),
        ),
        migrations.AlterField(
            model_name='menteerolefield',
            name='field',
            field=models.IntegerField(choices=[(1, 'CSE'), (2, 'ECE'), (3, 'CSD'), (4, 'CSAM'), (5, 'CSSS'), (6, 'CSAI')], null=True),
        ),
        migrations.AlterField(
            model_name='mentorexpectedrolefield',
            name='field',
            field=models.IntegerField(choices=[(1, 'CSE'), (2, 'ECE'), (3, 'CSD'), (4, 'CSAM'), (5, 'CSSS'), (6, 'CSAI')], null=True),
        ),
        migrations.AlterField(
            model_name='mentorrolefield',
            name='field',
            field=models.IntegerField(choices=[(1, 'CSE'), (2, 'ECE'), (3, 'CSD'), (4, 'CSAM'), (5, 'CSSS'), (6, 'CSAI')], null=True),
        ),
        migrations.CreateModel(
            name='MentorshipRequestMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop', models.TextField(max_length=512, null=True)),
                ('expectations', models.TextField(max_length=256, null=True)),
                ('commitment', models.TextField(max_length=256, null=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentor')),
            ],
        ),
    ]
