# Generated by Django 3.1.3 on 2020-12-22 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20201222_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteerolefield',
            name='mentee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.mentee'),
        ),
    ]
