# Generated by Django 3.1.3 on 2020-12-22 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20201222_0530'),
        ('users', '0028_auto_20201222_0117'),
    ]

    operations = [
    ]
