# Generated by Django 3.1.3 on 2020-12-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20201222_1016'),
        ('users', '0029_merge_20201222_0820'),
    ]

    operations = [
    ]
