# Generated by Django 3.1.3 on 2020-12-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20201231_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='social_handles',
        ),
        migrations.AddField(
            model_name='account',
            name='social_handle',
            field=models.URLField(help_text='Link to your personal website/LinkedIn profile', null=True),
        ),
    ]
