# Generated by Django 3.1.3 on 2021-01-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_deletedmentormenteerelation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletedmentormenteerelation',
            old_name='reason',
            new_name='end_reason',
        ),
    ]
