# Generated by Django 3.1.3 on 2021-01-07 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_accountresearchexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounteducation',
            old_name='education',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='accountresearchexperience',
            old_name='research_experience',
            new_name='details',
        ),
        migrations.AddField(
            model_name='accounteducation',
            name='end_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounteducation',
            name='organization',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounteducation',
            name='qualification',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounteducation',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountresearchexperience',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountresearchexperience',
            name='organization',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountresearchexperience',
            name='position',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountresearchexperience',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
