# Generated by Django 3.1.3 on 2021-02-19 19:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20210113_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedMentorshipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_reason', models.TextField(max_length=512)),
                ('date_ended', models.DateTimeField(default=django.utils.timezone.now)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentor')),
            ],
        ),
    ]
