# Generated by Django 3.1.3 on 2021-03-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20210219_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
