# Generated by Django 3.1.3 on 2021-03-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_mentor_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='other_responsibility',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
