# Generated by Django 3.1.3 on 2021-04-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20210310_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
